django_practise1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.urls import re_path as url
from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('', include('user.urls')),
    path('', include('home.urls')),
    path("accounts/", include("allauth.urls")),
    path('api-schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api-schema/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),


    # set up an API with ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
urlpatterns += url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

home/urls.py
from django.urls import path
from home import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('login-api/', obtain_auth_token),
    path('api/register/', views.RegisterView.as_view()),
    path('api/login/', views.LoginView.as_view()),
    path('api/user/', views.UserView.as_view()),
    path('api/logout/', views.LogoutView.as_view()),
]

user/urls.py
from django.urls import path
from user import views, ajax

app_name = 'user'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path("logout/", views.logout, name="logout"),
    path("register/check/username/", ajax.check_username, name="check_username"),
    path("register/check/email/", ajax.check_email, name="check_email"),
    path("register/check/dob/", ajax.check_dob, name="check_dob"),

]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from user.functions import check_request_type
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.exceptions import AuthenticationFailed
from .serializers import UserSerializer

from django.contrib.auth.models import User
import jwt, datetime


# Create your views here.
def index(request):
    is_login, flag_admin = check_request_type(request)

    context = {
        'is_login': is_login,
        'flag_admin': flag_admin,
    }

    return render(request, 'home/index.html', context)


class RegisterView(APIView):
    def post(self, request):
        serializer = UserSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    

class LoginView(APIView):
    def post(self, request):
        email = request.data['email']
        password = request.data['password']

        user = User.objects.filter(email=email).first()

        if user is None:
            raise AuthenticationFailed("User not found!")
        
        if not user.check_password(password):
            raise AuthenticationFailed("Incorrect password!")
        
        payload = {
            'id': user.id,
            'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=60),
            'iat': datetime.datetime.utcnow()
        }

        token = jwt.encode(payload, 'secret', algorithm='HS256')
        # print(token.decode('utf-8'))

        response = Response()
        response.set_cookie(key='jwt', value=token, httponly=True)
        response.data = {
            'message': "Login successful!",
            'jwt': token
        }
        
        return response
    

class UserView(APIView):
    def get(self, request):
        token = request.COOKIES.get('jwt')

        if not token:
            raise AuthenticationFailed("Unauthenticated!")
        
        try:
            payload = jwt.decode(token, 'secret', algorithms=['HS256'])
        except:
            raise AuthenticationFailed("Unauthenticated!")
        
        user = User.objects.filter(id=payload['id']).first()

        serializer = UserSerializer(user)

        return Response(serializer.data)
    

class LogoutView(APIView):
    def post(self, request):
        response = Response()
        response.delete_cookie('jwt')

        response.data = {
            'message': "Logout Successful!"
        }
        return response

home/templates/home/account_activation_email.html
{% autoescape off %}
Chào {{ user.username }},

    <p>Email này được gửi từ Sample.</p>
    
    Để kích hoạt tài khoản của bạn, vui lòng truy cập đường dẫn bên dưới.

    http://{{ domain }}{% url 'home:activate' uidb64=uid token=token %}

    Trân trọng.

{% endautoescape %}

home/templates/home/login.html
{% extends "home/base.html" %}
{% load static %}

<!-- Title -->
{% block title %} Home {% endblock %}

<!-- Content -->
{% block content %}
    <!-- User -->
    <div class="user-area ptb-100">
        <div class="container">
            <div class="user-item">
                <form method="POST">
                    {% csrf_token %}
                        <h2>Login</h2>
                    {% if message %}
                        <p class="text-center" style="color: red;">{{message}}</p>
                    {% endif %}
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Your Email/Username:" name="username_or_email">
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control" placeholder="Password:" name="password">
                    </div>
                    <h5 class="pb-3"><a href="">Forgot Password?</a></h5>
                    <button type="submit" class="btn common-btn">
                        Login
                    </button>
                    <h4>Or</h4>
                    <ul>
                        <li>
                            <a href="#">
                                <i class='bx bxl-facebook'></i>
                                Login With Facebook
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class='bx bxl-google'></i>
                                Login With Google
                            </a>
                        </li>
                    </ul>
                    <h5>Didn't Have An Account? <a href="{% url 'user:register' %}">Register</a></h5>
                </form>
            </div>
        </div>
    </div>
    <!-- End User -->

{% endblock %}

home/templates/home/product_change.html
{% extends "home/base.html" %}
{% load static %}

<!-- Title -->
{% block title %} Product-change {% endblock %}

{% block content %}
<!-- Form -->
<div class="about-area pt-100">
    <div class="container">
        <div class="row">
            <div class="col-xl">
                <div class="card mb-4">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <h5 class="mb-0">Thêm tài liệu</h5>
                    </div>
                    <div class="card-body">
                        <form class="needs-validation" method="post"
                            enctype="multipart/form-data">
                            {% csrf_token %}
        
                            <div class="mb-3">
                                <label for="title" class="form-label">Tiêu đề</label>
                                <input type="text" id="title" class="form-control" placeholder="Nhập tiêu đề" name="title"
                                   value="{{ product.title }}" required />
                            </div>
                            <div class="mb-3">
                                <label for="description" class="form-label">Mô tả</label>
                                <textarea type="text" id="description" name="description" class="form-control"
                                    placeholder="Nhập mô tả">{{ product.description|safe }}</textarea>
                            </div>
                            <div class="mb-3">
                                <label for="type" class="form-label">Category</label>
                                {% for category in categories %}
                                <select id="type" class="form-select" name="type" multiple>
                                    <option value="{{ category.codename }}">{{ category.name }}</option>
                                </select>
                                {% endfor %}
                            </div>
        
        
                            <div class="row g-2">
                                <div class="col-lg-6 col-md-6 col-sm-12 mb-3">
                                    <label class="form-label" for="photo">Ảnh bìa <red class="text-danger">*</red></label>
                                    <input name="photo" type="file" id="photo" class="dropify" data-height="100"
                                        accept="image/*" multiple required />
                                </div>
                                <!-- <div class="col-lg-6 col-md-6 col-sm-12 mb-3">
                                    <label class="form-label" for="pdfDoc">File PDF <red class="text-danger">*</red></label>
                                    <input name="source" type="file" id="pdfDoc" class="dropify" data-height="100" accept=".pdf"
                                        required />
                                </div> -->
                            </div>
        
                            <button type="submit" class="btn btn-primary" onclick="submitForm()">Lưu</button>
                            &nbsp;
                            <a href="#" class="btn btn-secondary">Hủy</a>
                        </form>
        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    // $(document).ready(function() {
    //     // Basic
    //     $('.dropify').dropify({
    //         messages: {
    //             default: 'Drag and drop or Click to change',
    //             replace: 'Drag and drop or Click to change',
    //             remove: 'Delete',
    //             error: 'Error exist'
    //         }
    //     });
    //     // Used events
    //     var drEvent = $('#input-file-events').dropify();

    //     drEvent.on('dropify.beforeClear', function (event, element) {
    //         return confirm("Do you really want to delete \"" + element.file.name + "\" ?");
    //     });

    //     drEvent.on('dropify.afterClear', function (event, element) {
    //         alert('File deleted');
    //     });

    //     drEvent.on('dropify.errors', function (event, element) {
    //         console.log('Has Errors');
    //     });

    //     var drDestroy = $('#input-file-to-destroy').dropify();
    //     drDestroy = drDestroy.data('dropify')
    //     $('#toggleDropify').on('click', function (e) {
    //         e.preventDefault();
    //         if (drDestroy.isDropified()) {
    //             drDestroy.destroy();
    //         } else {
    //             drDestroy.init();
    //         }
    //     })
    // });

</script>



{% endblock %}

home/templates/home/products.html
{% extends "home/base.html" %}
{% load static %}

<!-- Title -->
{% block title %} Product {% endblock %}

{% block content %} 
<div class="banner-area">
    <div class="banner-shape">
        <img src="{% static 'home/images/banner/shape1.png' %}" alt="Shape" class="one" data-speed="0.08" data-revert="true">
        <img src="{% static 'home/images/banner/shape2.png' %}" alt="Shape" class="two" data-speed="0.08" data-revert="true">
        <img src="{% static 'home/images/banner/shape3.png' %}" alt="Shape" class="three" data-speed="0.08" data-revert="true">
        <img src="{% static 'home/images/banner/shape4.png' %}" alt="Shape" class="four" data-speed="0.08" data-revert="true">
    </div>
</div>
<section>
    <div class="about-area pt-100">
        <div class="container">
            <table class="table table-striped table-bordered table-sm">  
                <thead class="thead-dark">  
                <tr>  
                    <th>ID</th>  
                    <th>Category</th>  
                    <th>Product</th>
                    <th>Create Date</th>  
                    <th>Is Enable</th>  
                    <th>Actions</th>  
                </tr>  
                </thead>  
                <tbody>  
            {% for product in products %}  
                <tr>  
                    <td>{{ product.id }}</td>  
                    <td>{{ product.title }}</td>
                    <td>{{ product.category.codename }}</td>  
                    <td>{{ product.create_date }}</td>  
                    <td>{{ product.is_enable }}</td>  
                    <td>  
                        <a href="/products/{{ product.id }}"><span class="glyphicon glyphicon-pencil">Edit</span></a>
                        &nbsp;  
                        <a href="/delete/{{ product.id }}"><span class="glyphicon glyphicon-trash">Delete</span></a>  
                    </td>  
                </tr>  
            {% endfor %}  
                </tbody>  
            </table>  
        </div>
    </div>
</section>


{% endblock %}

home/templates/home/register.html
{% extends "home/base.html" %}
{% load static %}

<!-- Title -->
{% block title %} Home {% endblock %}

<!-- Content -->
{% block content %}

    <!-- User -->
    <div class="user-area ptb-100">
        <div class="container">

            <div class="user-item">
                <form method="POST" id="register-form">
                    {% csrf_token %}
                    <h2>Register</h2>

                    {% if message %}
                    <div class="col-lg-12 col-md-12">
                        <div role="alert" class="alert alert-danger alert-dismissible">
                        <strong><i class="fa fa-exclamation-circle"></i></strong> {{message}} </div>
                    </div>
                    {% endif %}

                    <div class="form-group row">
                        <div class="col-sm-6">
                            <input type="text" class="form-control" placeholder="First Name:" name="firstname" required>
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" placeholder="Last Name:" name="lastname" required>
                        </div>
                    </div>

                    <!-- CHECK USERNAME -->
                    <div class="form-group">
                        <div class="form-check-info">
                            <input id="username" class="form-control" type="text" placeholder="User Name:" name="username" pattern="^[_A-z0-9]{3,}$" minlength="4" maxlength="24" required>                         
                            <span id="icon-success1" style="color: green; display: none;"><i class="fas fa-check-circle"></i></span>
                            <span id="icon-fail1" style="color: red; display: none;"><i class="fas fa-exclamation-circle"></i></span>
                        </div>
                        <div id="checkusername" class="message"></div>
                    </div>
                    <!-- END CHECK USERNAME -->

                    <!-- CHECK EMAIL -->
                    <div class="form-group">
                        <div class="form-check-info">
                            <input id="email" type="email" class="form-control" placeholder="Your Email:" name="email" required>
                            <span id="icon-success2" style="color: green; display: none;"><i class="fas fa-check-circle"></i></span>
                            <span id="icon-fail2" style="color: red; display: none;"><i class="fas fa-exclamation-circle"></i></span>
                        </div>
                        <div id="checkemail" class="message"></div>
                    </div>
                    <!-- END CHECK EMAIL -->

                    <!-- CHECK DOB -->
                    <div class="form-group">
                        <div class="form-check-info">
                            <input id="dob" type="date" class="form-control" placeholder="Date of Birth:" name="dob" required min="1900-01-01">
                            <span id="icon-success4" style="color: green; display: none;"><i class="fas fa-check-circle"></i></span>
                            <span id="icon-fail4" style="color: red; display: none;"><i class="fas fa-exclamation-circle"></i></span>
                        </div>
                        <div id="checkdob" class="message"></div>
                    </div>
                    <!-- END CHECK DOB -->

                    <!-- CHECK PASSWORD -->
                    <div class="form-group">
                        <div class="form-check-info">
                            <input id="password1" type="password" class="form-control" minlength="8" maxlength="24" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,24}$" placeholder="Password:" id="password1" name="password1" required>
                            <span id="icon-success3" style="color: green; display: none;"><i class="fas fa-check-circle"></i></span>
                            <span id="icon-fail3" style="color: red; display: none;"><i class="fas fa-exclamation-circle"></i></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-check-info">
                            <input type="password" class="form-control" placeholder="Confirm Password:" id="password2" name="password2" data-match="#password1" minlength="8" maxlength="24" required>
                            <span id="icon-success5" style="color: green; display: none;"><i class="fas fa-check-circle"></i></span>
                            <span id="icon-fail5" style="color: red; display: none;"><i class="fas fa-exclamation-circle"></i></span>
                            <span><em id="checkpasswordmatch" class="text-danger"></em></span>
                        </div>
                    </div>
                    <!-- END CHECK PASSWORD -->

                    <div id="message" class="notify-register" style="margin-bottom: 10px;">
                        <p id="letter" class="invalid">Mật khẩu chứa ít nhất một kí tự <b>viết thường</b></p>
                        <p id="capital" class="invalid">Mật khẩu chứa ít nhất một kí tự <b>viết hoa</b></p>
                        <p id="number" class="invalid">Mật khẩu chứa ít nhất một kí tự <b>số</b></p>
                        <p id="special" class="invalid">Mật khẩu chứa ít nhất một kí tự <b>đặc biệt</b></p>
                        <p id="minlength" class="invalid">Mật khẩu phải chứa ít nhất <b>8 kí tự</b></p>
                        <p id="checkpass2" class="invalid">Mật khẩu nhập lại phải <b>trùng khớp</b></p>
                    </div>

                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault4" name="flexCheckDefault4">
                            <label class="form-check-label" for="flexCheckDefault4">
                                I accept all <a href="#">Terms & Conditions</a>
                            </label>
                        </div>
                    </div>

                    <button type="submit" class="btn common-btn" id="register" style="opacity:0.5 !important" disabled>
                        Register
                    </button>

                    <h4>Or</h4>

                    <ul>
                        <li>
                            <a href="#">
                                <i class='bx bxl-facebook'></i>
                                Register With Facebook
                            </a>
                        </li>
                        <li>
                            {% load socialaccount %}
                            <a href="{% provider_login_url 'google' %}?next=/">
                                <i class='bx bxl-google'></i>
                                Register With Google
                            </a>
                        </li>
                    </ul>

                    <h5>Already Have An Account? <a href="{% url 'user:login' %}">Login</a></h5>

                </form>
            </div>

        </div>
    </div>
    <!-- End User -->

    {% block js %}
    <script src="{% static 'home/js/check_register.js' %}"></script>
    {% endblock %}

{% endblock %}

home/templates/home/verify-account.html
{% extends "home/base.html" %}
{% load static %}

<!-- Title -->
{% block title %} Home {% endblock %}

<!-- Content -->
{% block content %}
    <!-- Error -->
    <div class="error-area ptb-100">
        <div class="d-table">
            <div class="d-table-cell">
                <div class="container">
                    <div class="error-item">
                        <h1 langKey="v_account1">Chào bạn,</h1>
                        <p langKey="v_account2">Chúng tôi đã gửi email kích hoạt tài khoản đến địa chỉ mail mà bạn đã đăng kí. Vui lòng kiểm tra email để kích hoạt tài khoản.</p>
                        <a class="common-btn" href="{% url 'home:index' %}" langKey="v_account3">Trở về trang chủ</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Error -->
{% endblock %}